/**
 * Catalogo inicial estavel. Os codigos podem ser enviados futuramente ao
 * suporte sem expor tracking, recebedor, documento ou credenciais.
 */
export const CODIGOS_ERRO = {
  FIREBASE_CONECTIVIDADE: "DH-SYNC-S01-CONEXAO",
  FIREBASE_ASSINATURA: "DH-SYNC-S01-ASSINATURA",
  FIREBASE_HTTP_PERMANENTE: "DH-SYNC-S02-HTTP",
  PROJECAO_LOCAL: "DH-SYNC-S03-PROJECAO",
  INTERFACE_SINCRONIZACAO: "DH-SYNC-S04-INTERFACE",
  CACHE_CARGA_ADMIN: "DH-LOAD-S01-CACHE",
  PONTE_ANDROID: "DH-NAT-S02-PONTE",
  PLATAFORMA_NAO_SUPORTADA: "DH-NAT-S02-PLATAFORMA",
  CONTRATO_INTEGRACAO: "DH-INT-S01-CONTRATO",
  DEEP_LINK_TRANSPORTADORA: "DH-INT-S02-DEEPLINK",
  FALLBACK_CLIPBOARD: "DH-INT-S03-CLIPBOARD",
  TELEMETRIA_INTEGRACAO: "DH-INT-S04-TELEMETRIA",
} as const;

export type CodigoErroDeliveryHub = typeof CODIGOS_ERRO[keyof typeof CODIGOS_ERRO];
